services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html